version: "3.9"

services:
  minio:
    image: minio/minio
    container_name: minio-dev
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Console Web
    volumes:
      - ./.data/minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      # habilita CORS global para seu front
      MINIO_API_CORS_ALLOW_ORIGIN: http://localhost:5174,http://127.0.0.1:5174
    command: server /data --console-address ":9001"

  # (opcional) exemplo de postgres
  postgres:
    image: postgres:16
    container_name: pg-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prontuario
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data