services:
  minio:
    image: minio/minio:latest
    container_name: minio-dev
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_API_CORS_ALLOW_ORIGIN: http://localhost:5174,http://127.0.0.1:5174
    command: server /data --console-address ":9001"
